# Generated by Django 3.2.7 on 2021-10-04 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('do', '0002_do_date_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='do',
            name='checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='do',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
