# Generated by Django 3.2.7 on 2021-10-04 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('do', '0003_auto_20211004_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='do',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
